### PR TITLE
Collect separate mount info from separate units

### PR DESCRIPTION
**Pull request by cjwatson**
When migrating between NFS units (for redeployment or for vertical
scaling), there will be a period when an old unit still exists but
doesn't publish data on the relation.  Using the combined
`relation.joined_units` view makes it impossible to support this kind of
migration, as the old unit's `private-address` will always win.

The reactive documentation advises that it's normally better to iterate
over each unit and handle its data individually, and that indeed behaves
better in this case.  Nothing changes in the common case where there's
only a single NFS unit, and the requiring charm already typically has to
pick out the first response that meets its needs so isn't likely to be
confused by this change.

### CODE REVIEW

**Comment by cjwatson** [comment]
This has a minor conflict with #4, but I'm happy to rebase whichever one of these two PRs lands second.

**Review by johnsca — COMMENTED** [review]
I'm unclear on how this is intended to solve the migration scenario.  It seems like this would lead to two almost identical entries for all mounts which differ only by the `hostname` and it would then be up to the requiring side to try to guess which one it should actually use (presumably the first one it sees, which seems like it would be equivalent to the current behavior).

Since the interface already supports the NFS charm manually providing an explicit `hostname` value, it seems like a better solution would be to have the NFS charm figure out what the new unit is and override the `hostname` field for all units to point to the new one.  Then, the interface and requires sides don't need to change or care about the upgrade, other than handling the new `hostname` value as they should presumably do already.

**Comment by cjwatson** [comment]
The migration procedure I tested with a modified NFS charm (https://github.com/hyperbolic2346/nfs-charm/pull/7) was as follows:

 * set `active_units` to the old unit, thereby ensuring that only that unit is published
 * add the new unit
 * set `active_units` to "none", beginning downtime (no units are published)
 * wait for clients to unmount, then move storage to new unit
 * set `active_units` to the new unit; now only one unit is published but it's the new one
 * wait for clients to mount
 * remove the old unit, after which it's safe to unset the `active_units` configuration key

It's a little clunky, but without doing full-blown NFS clustering or something I'm not sure we can do much better; one way or another clients have to be told to unmount before the export can be removed from the old unit, storage moved to the new unit, and clients told to mount again.

The difference that this PR makes is that it now only collects information from units where `mountpoint`, `fstype`, and `options` are all set, rather than checking that after merging.  This allows the NFS charm to implement the notion of a present but inactive unit by setting those bits of relation data to `None`.  If the procedure above is used, no guesswork is needed on the requiring side, since at most one unit publishes a complete set of relation data at any given time.

FWIW, the only users I could find of this interface were various forks of the "kubernetes-worker" charm, which already picks the first NFS mount it gets back from `mount_relation.mounts()`; so I don't think this PR would require any change there.

I can see that it might be useful to provide an explicit `hostname` as you suggest (we'd need to make a small change to `provides.py` in this interface to permit that, and some kind of downtime configuration would still be necessary to allow storage to be moved around).  But this only works if the NFS charm can figure out something to put in the `hostname` field, and I can't work out how to actually implement that.  Is there any way for one unit in an application to discover the `private-address` of other units?  The only way I've been able to find is to require some kind of relation between the application and itself so that it can use `relation-get`, which seems odd to me.

**Comment by cjwatson** [comment]
Adam Collard pointed out that I could use a peer relation to get the address of other units, so I've reworked https://github.com/hyperbolic2346/nfs-charm/pull/7 to do that.

**Review by johnsca — APPROVED** [review]
Given the other PRs and clarification, this is a good cleanup to include.

**Pull request merged**
